// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LocalTokenGroup, LRParser } from '@lezer/lr';

import { jsonHighlighting } from './highlight';
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "'tOVQPOOOqQPO'#CbOyQPO'#ClOOQO'#Co'#CoO!QQQO'#CnOOQO'#Cx'#CxQOQPOOO!]OWO'#CmOOQO'#Cd'#CdO!kQPO'#CcO!pQPO'#C{OOQO,58|,58|O!xQPO,58|O!}OWO'#CeO#]QPO'#DWOOQO,59W,59WO#eQPO,59WO#jQSO'#DQOOQO'#Cr'#CrO!QQQO,59YOOQO'#Cp'#CpOOQO,59Y,59YO#uQQO'#CgOOOO'#Cq'#CqO$QOWO,59XOOQO,59X,59XOVQPO,58}OtQPO'#CsO$`QPO,59gOOQO1G.h1G.hO$hOWO,59POOQO,59P,59POVQPO'#CtO$vQPO,59rOOQO1G.r1G.rOOQO,59l,59lO%OQSO,59lOOQO-E6p-E6pOOQO1G.t1G.tO#uQQO,59ROOOO'#Ci'#CiOOOO,59R,59ROOOO-E6o-E6oOOQO1G.s1G.sOOQO1G.i1G.iOOQO,59_,59_OOQO-E6q-E6qOOQO1G.k1G.kOOQO,59`,59`OOQO-E6r-E6rOOQO1G/W1G/WOOOO1G.m1G.m",
  stateData:
    '%Z~OkOS~OQTORTOSTOTTO_QOnPOpVO{RO~OmZOp]O~O^_O~PVOrdOsbOuaO~OYgO[fOqgOwiO~OxjO~OykOmoX~OmmO~OYgO[fOqgOwoO~OypO^zX~O^rO~OsbOuaOvsO~OrxOsbOuaO~OYgO[fOqgOw{O~OykOmoa~OYgO[fOqgOw!PO~OypO^za~OsbOuaOv!SO~O',
  goto: '$[{PPPPPP|!S!Y!^P!bP!hPP|||!n!t!z#U#d#jPPP#pPP#|PPPP$PPPPPP$XXTOQjpQYPR}kTXPkTWPkXgV]hnQyfR!TwXSOQjpQeSRvcQhVQn]TzhnQcSQtaUuctwRwfQlYR!OlQq^R!RqQUOQ^QQ|jR!QpR[P]bSacftwR`Q',
  nodeNames:
    '⚠ JsonText True False Null Number Object Property PropertyName PropertyTemplateString Escape Interpolation InterpolationStart InterpolationEnd ] [ Array TemplateString Env EnvStart EnvEnd',
  maxTerm: 43,
  nodeProps: [
    ['closedBy', 12, 'InterpolationEnd', 15, ']', 19, 'EnvEnd'],
    ['openedBy', 13, 'InterpolationStart', 14, '[', 20, 'EnvStart'],
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData:
    "({~RlXY!yYZ!y]^!ypq!yqr#Ors#Tst#Otu#[u|#O|}#i}!O#p!O!Q#O!Q!R%l!R![%|![!]&a!]!}#O!}#O&h#O#P#O#P#Q&o#Q#Y#O#Y#Z&v#Z#b#O#b#c'g#c#h#O#h#i(Q#i#o#O#o#p(k#q#r(r~#OOk~[#TOs[^#[OpQs[^#aPs[#o#p#dQ#iO{Q^#pOyQs[^#uQs[!Q!R#{!R![%ZQ$QRTQ!O!P$Z!g!h$o#X#Y$oQ$^P!Q![$aQ$fRTQ!Q![$a!g!h$o#X#Y$oQ$rR{|${}!O${!Q![%RQ%OP!Q![%RQ%WPTQ!Q![%RQ%`STQ!O!P$Z!Q![%Z!g!h$o#X#Y$o^%sRTQs[!O!P$Z!g!h$o#X#Y$o^&TSTQs[!O!P$Z!Q![%Z!g!h$o#X#Y$o^&hOxQs[^&oO_Qs[^&vO^Qs[^&{Ps[#T#U'OQ'RP#`#a'UQ'XP#g#h'[Q'_P#X#Y'bQ'gORQ^'lPs[#i#j'oQ'rP#`#a'uQ'xP#`#a'{Q(QOSQ^(VPs[#f#g(YQ(]P#i#j(`Q(cP#X#Y(fQ(kOQQ^(rOu[nQ^({OrSmQvW",
  tokenizers: [
    1,
    2,
    3,
    new LocalTokenGroup(
      '#d~RRrs[tua#O#Pl~aOw~~dP#o#pg~lO[~~oXrs![!P!Q![#O#P![#U#V![#Y#Z![#b#c![#f#g![#h#i![#i#j!a~!aOY~~!dR!Q![!m!c!i!m#T#Z!m~!pR!Q![!y!c!i!y#T#Z!y~!|R!Q![#V!c!i#V#T#Z#V~#YR!Q![![!c!i![#T#Z![~',
      111,
      33,
    ),
  ],
  topRules: { JsonText: [0, 1] },
  tokenPrec: 0,
});
