/* eslint-disable prettier/prettier */
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { styleTags, tags } from '@lezer/highlight';
import { LocalTokenGroup, LRParser } from '@lezer/lr';

const jsonHighlighting = styleTags({
  String: tags.string,
  Number: tags.number,
  "True False": tags.bool,
  PropertyName: tags.propertyName,
  Null: tags.null,
  ",": tags.separator,
  "[ ]": tags.squareBracket,
  "{ }": tags.brace,
  Env: tags.bool,
  InterpolationStart: tags.bool,
  InterpolationEnd: tags.bool,
});

// This file was generated by lezer-generator. You probably shouldn't edit it.
const parser = LRParser.deserialize({
  version: 14,
  states: "%vOVQPOOOqOSO'#CbO!PQQO'#CgO!XQPO'#ClOOQO'#Cu'#CuQOQPOOO!`QQO'#CdOOOO'#Cn'#CnO!hOSO,58|OOQO,58|,58|OOQO'#Ci'#CiO!vQPO'#ChO!{QPO'#C{OOQO,59R,59RO#TQPO,59RO#YQPO'#DPOOQO,59W,59WO#bQPO,59WOOQO'#Co'#CoO#gQQO,59OOOOO,59O,59OOOOO-E6l-E6lOOQO1G.h1G.hOVQPO,59SO!SQQO'#CpO#oQPO,59gOOQO1G.m1G.mOVQPO'#CqO#wQPO,59kOOQO1G.r1G.rOOQO-E6m-E6mOOOO1G.j1G.jOOQO1G.n1G.nOOQO,59[,59[OOQO-E6n-E6nOOQO,59],59]OOQO-E6o-E6o",
  stateData: "$P~OhOS~OQSORSOSSOTSOYQO_ROaSOjPO~OXUOkVOlVOnXO~OV]OpYO~O^`O~PVOVdOmbO~OXUOkVOlVOnfO~OqgO~OrhOVoX~OVjO~OrkO^sX~O^mO~OVoOmbO~OrhOVoa~OrkO^sa~O",
  goto: "#VtPPPPPPuP{PPu!P!VPPuP!Z!a!g!mPPP!sPPPPP#PPPP#SXSORgkTVPWQ[QRqhTZQhQWPReWQcURncQi[RriQl_RtlQTOQ_RQpgRskR^QRaR",
  nodeNames: "⚠ JsonText True False Null Number String } Env InterpolationStart { Object Property PropertyName ] [ Array Env",
  maxTerm: 35,
  nodeProps: [
    ["openedBy", 7,"{",14,"["],
    ["closedBy", 9,"InterpolationEnd",10,"}",15,"]"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: ".q~RkXY!vYZ!v]^!vpq!vrs!{tu&S|})d}!O)i!Q!R+c!R![+s![!],W!c!},]!}#O,b#P#Q,g#R#S,]#T#Y,]#Y#Z,l#Z#b,]#b#c-]#c#h,]#h#i-v#i#o,]#o#p.a#q#r.f$g;'S,];'S;=`.k<%lO,]~!{Oh~U#QWjQpq#jqr#jrs$Vs#O#j#O#P$[#P;'S#j;'S;=`%|<%lO#jS#mWpq#jqr#jrs$Vs#O#j#O#P$[#P;'S#j;'S;=`%|<%lO#jS$[OpSS$_Xrs#j!P!Q#j#O#P#j#U#V#j#Y#Z#j#b#c#j#f#g#j#h#i#j#i#j$zS$}R!Q![%W!c!i%W#T#Z%WS%ZR!Q![%d!c!i%d#T#Z%dS%gR!Q![%p!c!i%p#T#Z%pS%sR!Q![#j!c!i#j#T#Z#jS&PP;=`<%l#jU&XPmS#o#p&[Q&_Xpq&[qr&[s#O&[#O#P&z#P#q&[#q#r(l#r;'S&[;'S;=`)^<%lO&[Q&}Xrs&[!P!Q&[#O#P&[#U#V&[#Y#Z&[#b#c&[#f#g&[#h#i&[#i#j'jQ'mR!Q!['v!c!i'v#T#Z'vQ'yR!Q![(S!c!i(S#T#Z(SQ(VR!Q![(`!c!i(`#T#Z(`Q(cR!Q![&[!c!i&[#T#Z&[Q(qXaQpq&[qr&[s#O&[#O#P&z#P#q&[#q#r(l#r;'S&[;'S;=`)^<%lO&[Q)aP;=`<%l&[~)iOr~Q)lQ!Q!R)r!R![+QQ)wRTQ!O!P*Q!g!h*f#X#Y*fQ*TP!Q![*WQ*]RTQ!Q![*W!g!h*f#X#Y*fQ*iR{|*r}!O*r!Q![*xQ*uP!Q![*xQ*}PTQ!Q![*xQ+VSTQ!O!P*Q!Q![+Q!g!h*f#X#Y*fU+jRTQmS!O!P*Q!g!h*f#X#Y*fU+zSTQmS!O!P*Q!Q![+Q!g!h*f#X#Y*f~,]Oq~S,bOmS~,gO_~~,lO^~U,qPmS#T#U,tQ,wP#`#a,zQ,}P#g#h-QQ-TP#X#Y-WQ-]ORQU-bPmS#i#j-eQ-hP#`#a-kQ-nP#`#a-qQ-vOSQU-{PmS#f#g.OQ.RP#i#j.UQ.XP#X#Y.[Q.aOQQ~.fOY~~.kOV~S.nP;=`<%l,]",
  tokenizers: [1, 2, new LocalTokenGroup("$S~RRrs[tua#O#Pl~aOn~~dP#o#pg~lOX~~oVO#i!U#i#j!Z#j#l!U#l#m!v#m;'S!U;'S;=`#{<%lO!U~!ZOk~~!^S!Q![!j!c!i!j#T#Z!j#o#p#`~!mR!Q![!v!c!i!v#T#Z!v~!yR!Q![#S!c!i#S#T#Z#S~#VR!Q![!U!c!i!U#T#Z!U~#cR!Q![#l!c!i#l#T#Z#l~#oS!Q![#l!c!i#l#T#Z#l#q#r!U~$OP;=`<%l!U~", 141, 28)],
  topRules: {"JsonText":[0,1]},
  tokenPrec: 0
});

export { parser };
