/* eslint-disable prettier/prettier */
// This file was generated by lezer-generator. You probably shouldn't edit it.
import { styleTags, tags } from '@lezer/highlight';
import { LocalTokenGroup, LRParser } from '@lezer/lr';

const jsonHighlighting = styleTags({
  String: tags.string,
  Number: tags.number,
  "True False": tags.bool,
  PropertyName: tags.propertyName,
  Null: tags.null,
  TemplateString: tags.string,
  PropertyTemplateString: tags.propertyName,
  ",": tags.separator,
  "[ ]": tags.squareBracket,
  StringEnv: tags.bool,
  Env: tags.moduleKeyword,
  Interpolation: tags.moduleKeyword,
  "InterpolationStart InterpolationEnd  EnvStart EnvEnd": tags.moduleKeyword,
  // NOTE: This is a hack to get the highlighting to work
  "}": tags.moduleKeyword,
  Escape: tags.number,
});

// This file was generated by lezer-generator. You probably shouldn't edit it.
const parser = LRParser.deserialize({
  version: 14,
  states: "'[OVQPOOOqQPO'#CbOyQPO'#CmOOQO'#Cp'#CpO!QQQO'#CoOOQO'#Cy'#CyQOQPOOO!YOSO'#CnOOQO'#Cd'#CdO!hQPO'#CcO!mQPO'#C|OOQO,58|,58|O!uQPO,58|O!zOSO'#CeO#YQPO'#DTOOQO,59X,59XO#bQPO,59XOOQO'#Cs'#CsO!QQQO,59ZOOQO'#Cq'#CqOOQO,59Z,59ZO#gQQO'#ChOOOO'#Cr'#CrO#oOSO,59YOOQO,59Y,59YOVQPO,58}OtQPO'#CtO#}QPO,59hOOQO1G.h1G.hO$VOSO,59POOQO,59P,59POVQPO'#CuO$eQPO,59oOOQO1G.s1G.sOOQO-E6q-E6qOOQO1G.u1G.uO#gQQO,59SOOOO'#Cj'#CjOOOO,59S,59SOOOO-E6p-E6pOOQO1G.t1G.tOOQO1G.i1G.iOOQO,59`,59`OOQO-E6r-E6rOOQO1G.k1G.kOOQO,59a,59aOOQO-E6s-E6sOOOO1G.n1G.n",
  stateData: "$m~OlOS~OQTORTOSTOTTO`QOoPOqVOxRO~OnZOq]O~O__O~PVOZcOsaO~OYfO]eOrfOthO~OuiO~OvjOnpX~OnlO~OYfO]eOrfOtnO~OvoO_wX~O_qO~OZuOsaO~OYfO]eOrfOtxO~OvjOnpa~OYfO]eOrfOt|O~OvoO_wa~O",
  goto: "#{xPPPPPPy!P!V!ZPP!_P!ePPyyy!k!q!w#R#]#cPPP#iPP#uPPPPPP#xXTOQioQYPRzjTXPjTWPjXfV]gmQveR!PtXSOQioQdSRsbQgVQm]TwgmQbSSrbtRteQkYR{kQp^R!OpQUOQ^QQyiR}oR[PR`Q",
  nodeNames: "⚠ JsonText True False Null Number Object Property PropertyName PropertyTemplateString Escape } Interpolation InterpolationStart InterpolationEnd ] [ Array TemplateString Env EnvStart EnvEnd",
  maxTerm: 40,
  nodeProps: [
    ["closedBy", 13,"InterpolationEnd",16,"]",20,"EnvEnd"],
    ["openedBy", 14,"InterpolationStart",15,"[",21,"EnvStart"]
  ],
  propSources: [jsonHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 4,
  tokenData: "(w~RlXY!yYZ!y]^!ypq!yqr#Ors#Tst#Otu#[u|#O|}#i}!O#p!O!Q#O!Q!R%l!R![%|![!]&a!]!}#O!}#O&h#O#P#O#P#Q&o#Q#Y#O#Y#Z&v#Z#b#O#b#c'g#c#h#O#h#i(Q#i#o#O#o#p(k#q#r(p~#OOl~S#TOsSU#[OqQsSU#aPsS#o#p#dQ#iOxQU#pOvQsSU#uQsS!Q!R#{!R![%ZQ$QRTQ!O!P$Z!g!h$o#X#Y$oQ$^P!Q![$aQ$fRTQ!Q![$a!g!h$o#X#Y$oQ$rR{|${}!O${!Q![%RQ%OP!Q![%RQ%WPTQ!Q![%RQ%`STQ!O!P$Z!Q![%Z!g!h$o#X#Y$oU%sRTQsS!O!P$Z!g!h$o#X#Y$oU&TSTQsS!O!P$Z!Q![%Z!g!h$o#X#Y$oU&hOuQsSU&oO`QsSU&vO_QsSU&{PsS#T#U'OQ'RP#`#a'UQ'XP#g#h'[Q'_P#X#Y'bQ'gORQU'lPsS#i#j'oQ'rP#`#a'uQ'xP#`#a'{Q(QOSQU(VPsS#f#g(YQ(]P#i#j(`Q(cP#X#Y(fQ(kOQQ~(pOo~U(wOZSnQ",
  tokenizers: [1, 2, new LocalTokenGroup("#d~RRrs[tua#O#Pl~aOt~~dP#o#pg~lO]~~oXrs![!P!Q![#O#P![#U#V![#Y#Z![#b#c![#f#g![#h#i![#i#j!a~!aOY~~!dR!Q![!m!c!i!m#T#Z!m~!pR!Q![!y!c!i!y#T#Z!y~!|R!Q![#V!c!i#V#T#Z#V~#YR!Q![![!c!i![#T#Z![~", 111, 34)],
  topRules: {"JsonText":[0,1]},
  tokenPrec: 0
})



export { parser };
