// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {yaadeHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SQQOSOOO]OPO'#C_OOOO'#Ce'#CeOOOO'#Cb'#CbQQOSOOOhOQO'#CiOOOO'#Cc'#CcO]OPO,58yOOOO'#Ca'#CaOOOO,58y,58yOOOO-E6`-E6`OOOO,59T,59TOsOQO,59TOOOO-E6a-E6aOOOO1G.e1G.eOOOO1G.o1G.o",
  stateData: "!O~OQQOSPOYQO~OZWO[UO^TO~O[UO^TO_ZO~O[UO^TO__O~O",
  goto: "!T^PPP_PcioPyPPP}TQOSQXPR^VQSORYSQVPQ[TT]V[TROSXUPTV[",
  nodeNames: "⚠ Value Escape Interpolation InterpolationStart InterpolationEnd",
  maxTerm: 15,
  nodeProps: [
    ["closedBy", 4,"InterpolationEnd"],
    ["openedBy", 5,"InterpolationStart"]
  ],
  propSources: [yaadeHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "y~RVXYhYZh]^hpqhq#oh#o#pm#q#rr~mO[~~rO^~UyOZQ_S",
  tokenizers: [1, 2, new LocalTokenGroup("#[~RQtuX#O#Pd~[P#o#p_~dOS~~gXrs!S!P!Q!S#O#P!S#U#V!S#Y#Z!S#b#c!S#f#g!S#h#i!S#i#j!X~!XOQ~~![R!Q![!e!c!i!e#T#Z!e~!hR!Q![!q!c!i!q#T#Z!q~!tR!Q![!}!c!i!}#T#Z!}~#QR!Q![!S!c!i!S#T#Z!S~", 103, 10)],
  topRules: {"Value":[0,1]},
  tokenPrec: 0
})
