// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {yaadeHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jQQOQOOO]OPO'#C_OOOO'#Ce'#CeOOOO'#Cb'#CbQQOQOOOOOO'#Cc'#CcO]OPO,58yOOOO'#Ca'#CaOOOO,58y,58yOOOO-E6`-E6`OOOO-E6a-E6aOOOO1G.e1G.e",
  stateData: "e~OQQOSPOYQO~OZVO[TO~O",
  goto: "uYPPPZP_ekPqTQOSQWPRZUQSORXSQUPRYUTROS",
  nodeNames: "⚠ Value Escape Interpolation InterpolationStart InterpolationEnd",
  maxTerm: 12,
  nodeProps: [
    ["closedBy", 4,"InterpolationEnd"],
    ["openedBy", 5,"InterpolationStart"]
  ],
  propSources: [yaadeHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "o~RUXYeYZe]^epqeq#oe#q#rj~jO[~~oOZ~",
  tokenizers: [1, new LocalTokenGroup("#[~RQtuX#O#Pd~[P#o#p_~dOS~~gXrs!S!P!Q!S#O#P!S#U#V!S#Y#Z!S#b#c!S#f#g!S#h#i!S#i#j!X~!XOQ~~![R!Q![!e!c!i!e#T#Z!e~!hR!Q![!q!c!i!q#T#Z!q~!tR!Q![!}!c!i!}#T#Z!}~#QR!Q![!S!c!i!S#T#Z!S~", 103, 10)],
  topRules: {"Value":[0,1]},
  tokenPrec: 0
})
